language: android

sudo: false

jdk: oraclejdk8

notifications:
  email:
    - sebastian.kacprzak@byoutline.com

env:
  matrix:
    - ANDROID_TARGET=android-18  ANDROID_ABI=armeabi-v7a TERM=dumb

android:
  components:
    - tools
    - build-tools-27.0.1
    - platform-tools
    - android-27

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  # workaround for https://github.com/travis-ci/travis-ci/issues/8874
  - yes | sdkmanager "platforms;android-27"

script: ./gradlew check testDebugUnitTestCoverage -x lint coveralls